### ISSUE TITLE
error: ‘requires’ only available with ‘-fconcept

### ISSUE THREAD

**Issue by 1134128371** [marlam/wurblpt-mirror#3]
Exceptional work! I ran camsim successfully. but the wurblpt didn't work on my computer.  The software environment is:
Ubuntu 20.04
GCC 9.4.0
CMake 3.16.3

According to readme.md, I install libtgd and libwurblpt. When I ran the wurblpt-tof-example, the problems occur：

In file included from /usr/local/include/wurblpt/transformation.hpp:28,
                 from /usr/local/include/wurblpt/animation.hpp:33,
                 from /usr/local/include/wurblpt/scene.hpp:36,
                 from /usr/local/include/wurblpt/wurblpt.hpp:42,
                 from /home/fxw/so/wurblpt/wurblpt-tof-example/wurblpt-tof-example.cpp:32:
/usr/local/include/wurblpt/gvm.hpp:88:52: error: ‘requires’ only available with ‘-fconcepts’
   88 |     template<typename T> constexpr T min(T x, T y) requires (std::is_arithmetic_v<T>) { return (x < y ? x : y); }
      |                                                    ^~~~~~~~
/usr/local/include/wurblpt/gvm.hpp:93:52: error: ‘requires’ only available with ‘-fconcepts’
   93 |     template<typename T> constexpr T max(T x, T y) requires (std::is_arithmetic_v<T>) { return (x > y ? x : y); }
      |                                                    ^~~~~~~~
/usr/local/include/wurblpt/gvm.hpp:98:69: error: ‘requires’ only available with ‘-fconcepts’
   98 | plate<typename T> constexpr T clamp(T x, T minval, T maxval) requires (std::is_arithmetic_v<T>) { return min(maxval, max(minval, x)); }
      |                                                              ^~~~~~~~

In file included from /usr/local/include/wurblpt/transformation.hpp:28,
                 from /usr/local/include/wurblpt/animation.hpp:33,
                 from /usr/local/include/wurblpt/scene.hpp:36,
                 from /usr/local/include/wurblpt/wurblpt.hpp:42,
                 from /home/fxw/so/wurblpt/wurblpt-tof-example/wurblpt-tof-example.cpp:32:
/usr/local/include/wurblpt/gvm.hpp:100:56: error: ‘requires’ only available with ‘-fconcepts’
  100 |     template<typename T> constexpr T step(T edge, T x) requires (std::is_arithmetic_v<T>) { return (x < edge ? T(0) : T(1)); }
      |                                                        ^~~~~~~~
/usr/local/include/wurblpt/gvm.hpp:102:52: error: ‘requires’ only available with ‘-fconcepts’
  102 |     template<typename T> constexpr T mod(T x, T y) requires (std::is_integral_v<T>) { return x - (x / y) * y; }
      |                                                    ^~~~~~~~
/usr/local/include/wurblpt/gvm.hpp:103:52: error: ‘requires’ only available with ‘-fconcepts’
  103 |     template<typename T> constexpr T mod(T x, T y) requires (std::is_floating_point_v<T>) { return x - std::floor(x / y) * y; }
      |                                                    ^~~~~~~~
/usr/local/include/wurblpt/gvm.hpp:103:38: error: redefinition of ‘template<class T> constexpr T WurblPT::mod(T, T)’
  103 |     template<typename T> constexpr T mod(T x, T y) requires (std::is_floating_point_v<T>) { return x - std::floor(x / y) * y; }
      |                                      ^~~
......
In file included from /usr/local/include/wurblpt/wurblpt.hpp:49,
                 from /home/fxw/so/wurblpt/wurblpt-tof-example/wurblpt-tof-example.cpp:32:
/usr/local/include/wurblpt/texture_image.hpp: In function ‘WurblPT::Texture* WurblPT::createTextureImage(const TGD::ArrayContainer&, WurblPT::LinearizeSRGBType, const vec2&, const vec2&, const vec4&, const vec4&)’:
/usr/local/include/wurblpt/texture_image.hpp:270:27: error: expected type-specifier
  270 |                 tex = new TextureImage<1, TGD::uint8, true>(img, coordFactor, coordOffset, valFactor, valOffset);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/wurblpt/texture_image.hpp:272:27: error: expected type-specifier
  272 |                 tex = new TextureImage<1, TGD::uint8, false>(img, coordFactor, coordOffset, valFactor, valOffset);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/wurblpt/texture_image.hpp:275:27: error: expected type-specifier
  275 |                 tex = new TextureImage<1, TGD::uint16, true>(img, coordFactor, coordOffset, valFactor, valOffset);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/wurblpt/texture_image.hpp:277:27: error: expected type-specifier
  277 |                 tex = new TextureImage<1, TGD::uint16, false>(img, coordFactor, coordOffset, valFactor, valOffset);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.......

So, how to solve this problem?(perheps the gcc version problem?)

**Comment by marlam** [comment]
Yes, WurblPT uses C++ 2020, which gcc 9 does not yet fully support.

It should be sufficient to add `-fconcepts` to `CMAKE_CXX_FLAGS` with gcc 9. In the example programs, the `CMakeLists.txt` files already contain a line that modifies `CMAKE_CXX_FLAGS`. You can add `-fconcepts` there. For libwurblpt, you can add the same line at the end of the section Requirements in `CMakeLists.txt`.

Alternatively, you can use a newer version of gcc.

**Comment by 1134128371** [comment]
cool, add "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fconcepts") " in the CMakelists of Wurblpt-tof-example and libwurblpt. The solution is quite effective, but it causes another problem(I think it's  the last one) :

In file included from /usr/include/c++/9/cassert:44,
                 from /usr/local/include/wurblpt/geometryproc.hpp:28,
                 from /usr/local/include/wurblpt/mesh.hpp:33,
                 from /usr/local/include/wurblpt/scene.hpp:41,
                 from /usr/local/include/wurblpt/wurblpt.hpp:42,
                 from /home/fxw/so/wurblpt/wurblpt-tof-example/wurblpt-tof-example.cpp:32:
/usr/local/include/wurblpt/bvh.hpp: In static member function ‘static const WurblPT::BVHNode* WurblPT::BVHNode::buildBVH(size_t, std::vector<const WurblPT::Hitable*>, WurblPT::AnimationCache&, WurblPT::AnimationCache&)’:
/usr/local/include/wurblpt/bvh.hpp:183:13: error: ‘omp_get_supported_active_levels’ was not declared in this scope; did you mean ‘omp_get_max_active_levels’?
  183 |             assert(size_t(omp_get_supported_active_levels()) >= maxTreeDepth);
      |             ^~~~~~

Perheps, the openMP cause this problem? （Rebuild the openMP？）

**Comment by 1134128371** [comment]
Well, I try to use "omp_get_max_active_levels" in the bvh.hpp. I find this program(tof-example) can run, but i don't know whether the result is correct.

**Comment by marlam** [comment]
Yes, you can use `omp_get_max_active_levels` instead. The function was just renamed in newer versions of OpenMP.

This is in an `assert` statement, which means it is only used in Debug builds anyway.

You probably want to set `CMAKE_BUILD_TYPE` to `Release` to get vastly better performance.

**Comment by 1134128371** [comment]
Great, the method is very useful. Well done.
